version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - curl -fsSL https://rpm.nodesource.com/setup_18.x | bash - # Add Node.js repository
      - yum install -y nodejs # Use yum to install Node.js

  pre_build:
    commands:
      - echo Setting up project...
      - npm init -y # Initialize Node.js project
      - npm install # Install dependencies (if any)

  build:
    commands:
      - echo Running tests...
      - node multiply.test.js # Run the test script

artifacts:
  files:
    - '**/*'
